### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by AWbosman** [iurada/fairness_crossdomain#1]
Hi! 

I am trying to reproduce some part of your interesting work and just running your scripts from this repo. 
I have followed the installation guide etc but I get the following error when running your scripts:

```
Traceback (most recent call last):
  File "main.py", line 75, in <module>
    main()
  File "main.py", line 20, in main
    args = parse_arguments()
  File "x/fairness_crossdomain/parse_args.py", line 30, in parse_arguments
    exp_type = os.path.normpath(args.experiment).split(os.sep)[1]
IndexError: list index out of range
```
Can you help me with solving this? Or point me to where this error might originate?

**Comment by iurada** [comment]
Hello!

Thank you so much for the kind words! This error is a consequence of a (very bad) choice of input validation I did a while ago. The idea was to check that the user would run a task (eg. classification) only on the datasets that support it. I will work on a fix for this.

In the meantime, can you please share some more details about how you launched the experiments and your configuration (eg. os, python version...)

**Comment by iurada** [comment]
Hi again,

unfortunately, I have no longer access to the checkpoints. However, I pushed some really minor fixes and tried running the experiments again. If everything has been set up correctly, then you should be able to run the code by simply editing the launch scripts in the `scripts/` folder (eg. to reproduce the baseline on CelebA, with "EyeBags" as protected attribute, you can launch the experiment as `./scripts/celeba_eyebags_baseline.sh`. Just remember to change the file paths to suit your configuration).

Regarding the details, conda should definitely not be a problem.

Hope this can help!
